### PR TITLE
Manpages from Debian

### PR DESCRIPTION
**Pull request by lechner**
Would you like to ship the manpages from Debian? Thank you!

### CODE REVIEW

**Comment by jaymzh** [comment]
Yes please! Should we add them to the `setup.py` though? I know it doesn't handle them natively, but maybe like:

https://github.com/nose-devs/nose/blob/master/setup.py#L109 

?

**Comment by lechner** [comment]
Looks good! Unfortunately, my Python skills are limited, and I can install the manpages either way. Would you like an update to the pull request or do you know how it should be done? Thank you!

**Comment by jaymzh** [comment]
You should be able to just add:

```
  'data_files': [
    (
      'man/man1': [
        'doc/pius-keyring-mgr.1',
        'doc/pius.1',
        'doc/pius-report.1'
        'doc/pius-party-worksheet.1'
      ]
    )
  ]
```

Give it a shit and see if it installs the right files into the right places for you.

**Comment by lechner** [comment]
The last commit works on Debian. We install manpages in `/usr/share/man`. Please feel free to change it. Thank you!

**Comment by jaymzh** [comment]
Awesome, thanks!

**Pull request merged**
