### PR TITLE
continue on PROGRESS and PINENTRY_LAUNCHED

### PR DESCRIPTION
**Pull request by oleeander**
With this change Pius should be compatible with newer versions of GnuPG.

### CODE REVIEW

**Comment by malattiad** [comment]
I stumbled on this issue too. Please merge these changes.

**Comment by jaymzh** [comment]
Hey @oleeander - what version are you on? I don't see this with 2.1.9... which is strange.

**Comment by malattiad** [comment]
I have 2.1.9 on Debian. Maybe it's a patch applied to gnupg2 there?

I submitted this bug report to the Debian package too:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805649

On Friday, November 20, 2015, Phil Dibowitz <notifications@github.com>
wrote:

> Hey @oleeander <https://github.com/oleeander> - what version are you on?
> I don't see this with 2.1.9... which is strange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaymzh/pius/pull/20#issuecomment-158460873>.
>


-- 
mattia
:wq!

**Comment by jaymzh** [comment]
I'm also on Debian. Weird... Ah well, it's a good PR. Merging. Thanks!

**Comment by oleeander** [comment]
I'm on Arch Linux and GnuPG 2.1.9 with libgcrypt 1.6.4. They don't have any patches applied downsteam:
* https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gnupg
* https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libgcrypt

**Comment by jaymzh** [comment]
All good. Thanks for the PR!

**Pull request merged**
